baseURL = 'https://modern-pascal.netlify.app/'
locale = 'en-us'
title = 'Modern Pascal'
theme = 'PaperMod'

[params]
  description = "Exploring Delphi, Free Pascal, Object Pascal, and the Wirth lineage."
  ShowCover = true
  ShowPageCover = true

  [params.cover]
    image = "images/banner.jpg"
    alt = "Banner Image"
    caption = ""
    relative = false

